/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vr_RiftJNI */

#ifndef _Included_vr_RiftJNI
#define _Included_vr_RiftJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vr_RiftJNI
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vr_RiftJNI_start
  (JNIEnv *, jobject);

/*
 * Class:     vr_RiftJNI
 * Method:    getData
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_vr_RiftJNI_getData
  (JNIEnv *, jobject);

/*
 * Class:     vr_RiftJNI
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vr_RiftJNI_end
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
