/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_java_impl_Context */

#ifndef _Included_org_berkelium_java_impl_Context
#define _Included_org_berkelium_java_impl_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_java_impl_Context
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_berkelium_java_impl_Context__1init
  (JNIEnv *, jclass);

/*
 * Class:     org_berkelium_java_impl_Context
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_java_impl_Context__1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
