/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_java_impl_BufferImpl */

#ifndef _Included_org_berkelium_java_impl_BufferImpl
#define _Included_org_berkelium_java_impl_BufferImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_java_impl_BufferImpl
 * Method:    createIntArray
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_org_berkelium_java_impl_BufferImpl_createIntArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_berkelium_java_impl_BufferImpl
 * Method:    createByteArray
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_berkelium_java_impl_BufferImpl_createByteArray
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_berkelium_java_impl_BufferImpl
 * Method:    createByteBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_java_impl_BufferImpl_createByteBuffer
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
