/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_java_impl_SingleThreadBerkelium */

#ifndef _Included_org_berkelium_java_impl_SingleThreadBerkelium
#define _Included_org_berkelium_java_impl_SingleThreadBerkelium
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_java_impl_SingleThreadBerkelium
 * Method:    _init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_java_impl_SingleThreadBerkelium__1init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_berkelium_java_impl_SingleThreadBerkelium
 * Method:    _update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_java_impl_SingleThreadBerkelium__1update
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_java_impl_SingleThreadBerkelium
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_java_impl_SingleThreadBerkelium_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
