
BASE_DIR := ../../../..
OUT_DIR := $(BASE_DIR)/build/bin/release

RM := rm -rf

all: $(OUT_DIR)/WebFlow

$(OUT_DIR)/WebFlow: $(OUT_DIR)/libAwesomium.so $(OUT_DIR)/AwesomiumProcess
	@echo 'Building target: $@'
	g++ -w -I$(BASE_DIR)/include $(BASE_DIR)/samples/WebFlow/src/main.cpp $(BASE_DIR)/samples/WebFlow/src/Application.cpp $(BASE_DIR)/samples/WebFlow/src/WebTile.cpp `sdl-config --cflags --libs` -L$(OUT_DIR) -lAwesomium -Wl,-rpath=./ -lGL -lGLU -o $(OUT_DIR)/WebFlow
	@echo 'Finished building target: $@'
	@echo ' '

clean: 
	-$(RM) $(OUT_DIR)/WebFlow
	-$(RM) $(OUT_DIR)/WebFlow
	-@echo ' '
